### ISSUE TITLE
Myrtille cannot open remoteapp, but xfreerdp can

### ISSUE THREAD

**Issue by Sayi** [cedrozor/myrtille#305]
## Myrtille version
2.9.2_X86_X64

## Server version
Windows Server 2019（I also try Windows Server 2012 R2）

## Issue Description
Hi,

Myrtille cannot open remoteAPP，will show desktop:

```
http://XXX.XXX.X.XXX/Myrtille?__EVENTTARGET=&__EVENTARGUMENT=&server=AAA.AAA.A.AAA&domain=&user=admin&password=mypassword&program=D:\eclipse\eclipse\eclipse.exe&connect=Connect%21   ❌
```

encode url is also not work:

```
http://XXX.XXX.X.XXX/Myrtille?__EVENTTARGET=&__EVENTARGUMENT=&server=AAA.AAA.A.AAA&domain=&user=admin&password=mypassword&program=d%3A%5Ceclipse%5Ceclipse%5Ceclipse.exe&connect=Connect%21   ❌
```

Xfreerdp can, will show eclipse:

```bash
xfreerdp /u:admin  /v:AAA.AAA.A.AAA  /app:"D:\eclipse\eclipse\eclipse.exe" ✅
```

Xfreerdp use `/shell` cannot open, will show desktop:

```bash
xfreerdp /u:admin  /v:AAA.AAA.A.AAA  /shell:"D:\eclipse\eclipse\eclipse.exe"  ❌
```

I found some similar issues, the most similar is #137 ，But my server uses windows server2019.

Then I create remote APP with remoteAPP tool at rdp-server, xfreerdp can open remoteapp:
```bash
 xfreerdp /u:admin  /v:AAA.AAA.A.AAA /app:"||eclipse"   ✅

 xfreerdp /u:admin  /v:AAA.AAA.A.AAA /shell:"||eclipse"  ❌
```

Myrtille cannot:
```
http://XXX.XXX.X.XXX/Myrtille?__EVENTTARGET=&__EVENTARGUMENT=&server=AAA.AAA.A.AAA&domain=&user=admin&password=mypassword&program=||eclipse&connect=Connect%21   ❌
```

Regards,
Sayi

**Comment by cedrozor** [comment]
Hi Sayi, Myrtille doesn't use remoteapp but the alternate shell feature of RDP. This is because, historically, there were some issues with FreeRDP and remoteapp. Maybe this was fixed in the latest versions of FreeRDP; I have to update it with Myrtille anyway, so I will re-check this.

That said, did you allowed Eclipse among the allowed remote apps (https://www.beyondtrust.com/docs/privileged-identity/app-launcher-and-recording/installation/set-up-rds.htm)? or set the (local or domain) policy which allows to remote start any unlisted program (https://github.com/cedrozor/myrtille/issues/203)?

Also have a look at these:
- https://docs.microsoft.com/en-us/troubleshoot/windows-server/remote/application-not-start-in-remoteapp-session
- https://support.citrix.com/article/CTX218256

**Comment by Sayi** [comment]
Hi,

I set the local policy which allows to remote start any unlisted program according to your method, but it still doesn't seem to work.

Thank you for your reply anyway.

**Comment by Beej126** [comment]
> Myrtille doesn't use remoteapp but the alternate shell feature of RDP. This is because, historically, there were some issues with FreeRDP and remoteapp. Maybe this was fixed in the latest versions of FreeRDP; I have to update it with Myrtille anyway, so I will re-check this.

@cedrozor - this sounds like the same solve as my #339 question - any chance you've gotten to fiddle with this yet or suggest where i can hack around?

**Comment by cedrozor** [comment]
Hi, yes I have to find some time to integrate the latest FreeRDP code (and work again on Myrtille, more globally) and re-check if I can use remoteapp instead of alternate shell

**Comment by Beej126** [comment]
@cedrozor - just a friendly bump if you happen to be bored over the holidays =) any tips you could give off the top of your head, even conceptually, where/how to switch from alternate-shell to remote-app are appreciated. 

going by [FreeRDP/wiki/CommandLineInterface](https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface) i was hoping to see something about the /shell vs /app args being passed here in [Myrtille.Services/RemoteSessionProcess](https://github.com/cedrozor/myrtille/blob/b99671589ad0c18f7ccb0878d08e05bcb9cb15c6/Myrtille.Services/RemoteSessionProcess.cs#L329) but that piece doesn't seem to be included in this list of args - any help?
